# Generated by Django 5.1.5 on 2025-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hospital", "0003_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="custom_users_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Doctor", "Doctor"),
                    ("Patient", "Patient"),
                ],
                default="Patient",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_users_permissions",
                to="auth.permission",
            ),
        ),
    ]
