# Generated by Django 5.1.5 on 2025-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_alter_customuser_groups_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
