# Generated by Django 5.1.5 on 2025-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0006_doctors_user_patient_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
