# Generated by Django 5.1.5 on 2025-02-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hospital", "0007_patient_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.appointment",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="medical_report",
            field=models.FileField(blank=True, null=True, upload_to="medical_reports/"),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Finalized", "Finalized")],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Doctor", "Doctor"),
                    ("Patient", "Patient"),
                ],
                default="Patient",
                editable=False,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="medications",
            field=models.JSONField(default=list),
        ),
    ]
