# Generated by Django 5.1.5 on 2025-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0008_medicalrecord_appointment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
