# Generated by Django 5.1.5 on 2025-02-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0011_alter_medicalrecord_medications"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.appointment",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.doctors",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.patient",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Partially Paid", "Partially Paid"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
