# Generated by Django 5.1.5 on 2025-02-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0012_billing_appointment_billing_doctor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="paypal_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
